doctrine:
  dbal:
    default_connection: default
    connections:
      default:
        # configure these for your database server
        url: "%env(resolve:DATABASE_URL)%"
      univ:
        # configure these for your database server
        url: "%env(resolve:DATABASE_UNIV_URL)%"

  orm:
    default_entity_manager: default
    entity_managers:
      default:
        connection: default

        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        mappings:
          App:
            is_bundle: false
            dir: "%kernel.project_dir%/src/Entity"
            prefix: 'App\Entity'
            alias: App
      univ:
        connection: univ
